import { useState } from 'react';
import Head from 'next/head';
import { useDropzone } from 'react-dropzone';

export default function Home() {
  const [files, setFiles] = useState(null);
  const { getRootProps, getInputProps } = useDropzone({
    accept: 'image/*',
    onDrop,
  });

  function onDrop(files) {
    setFiles(
      files.map((file) =>
        Object.assign(file, {
          preview: URL.createObjectURL(file),
        })
      )
    );
  }

  console.log(files);

  return (
    <div>
      <Head>
        <title>Next Dropzone test</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div
        className="flex justify-center items-center w-full h-screen"
        {...getRootProps()}
      >
        <input {...getInputProps()} />
        {files ? (
          <div>
            {files.map((file) => (
              <div key={file.name}>
                <img src={file.preview} alt="preview" className="w-56" />
              </div>
            ))}
          </div>
        ) : (
          <p>Drop files here</p>
        )}
      </div>
    </div>
  );
}
